input {
  file {
    path => "/app/logs/*.log"
    start_position => "beginning"
    codec => plain
    sincedb_path => "/usr/share/logstash/data/sincedb_cbt"
  }
}

filter {
  if [message] =~ /^\s*$/ {
    drop { }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "cbt-logs-%{+YYYY.MM.dd}"
  }
}
